### PR TITLE
Update Newtonsoft.Json

### PR DESCRIPTION
**Pull request by btecu**

### CODE REVIEW

**Comment by kattrali** [comment]
Thanks for the contribution, @btecu. What does this improve?

**Comment by btecu** [comment]
@kattrali It allows `bugsnag-dotnet` to be used in a project that uses the latest version of `Newtonsoft.Json` without having to pull in multiple versions.

**Comment by martin308** [comment]
@btecu could you share some more details of your setup? 

If you are using VisualStudio and Nuget then it should setup the necessary binding redirects that will allow bugsnag to use newer versions of json.net. 

We are going to be making major changes to this library which will make this PR redundant but we are happy to help you getting bugsnag-dotnet working with your current setup

**Comment by btecu** [comment]
@martin308 Yes, I'm trying to avoid exactly that. I don't want to have to set the bindings.

I don't know when your major changes are going to happen, but it's been almost six months later since I've opened this and nothing else has been committed.

**Comment by martin308** [comment]
@btecu I have pushed what will become version 2 of this notifier https://github.com/bugsnag/bugsnag-dotnet/tree/v2. We have removed json.net so this shouldn't cause issues anymore. Let us know what you think

**Pull request closed without merging**
