### PR TITLE
Possible Mono Compatible Version

### PR DESCRIPTION
**Pull request by CodeHex**
This is my attempt to make a Mono Compatible version. It basically has a MonoRelease configuration that will remove the incompatible code and references at compile time. It will build `BugsnagMono.dll` so you can tell the difference between the dlls.

I've excluded the incompatible code and reference mentioned in issue #19, but haven't got round to testing it so have no idea if there are any other places which are not compatible. Will try to test it on Mac at some point.

### CODE REVIEW

**Comment by loopj** [comment]
So awesome!

**Comment by CodeHex** [comment]
Looks like all the WPF stuff needs to be excluded as Mono has no plans for supporting it. [Mono on WPF](http://www.mono-project.com/docs/gui/wpf/)

Also, the stack traces coming back look slightly different from the native .NET framework when rethrowing exceptions...need to look into further

**Comment by snmaynard** [comment]
Does the WPF client have any effect on Mono? Could you not just not initialise it - use a BaseClient instead?

**Comment by CodeHex** [comment]
It's just one line that's incompatible, really. I tried to build it using MonoDevelop on my Mac and this line failed.

https://github.com/bugsnag/bugsnag-dotnet/blob/master/src/Bugsnag.Core/Clients/WPFClient.cs#L18

I think it failed because it uses a WPF library which isn't supported. We could compile out this line or compile out the entire class incase there is any other specific WPF code added at a later point. 

The DLL will probably work if you just don't call WPFClient. Will try to verify this at some point.

**Comment by CodeHex** [comment]
Verified that the BaseClient in BugsnagMono.dll sends notifications, i.e. just don't use WPFClient! 

I've added some stuff to identify the Mac OS version. The mono implementation of `Environment.OSVersion`for Mac seems to be a little tricky depending on mono / .net version. Currently identifying version using `sw_vers` sent to a terminal using a `Process`. Not very familiar with Mac security so not sure if this ok?

**Comment by snmaynard** [comment]
It seems completely sensible to me for now. I think I'll merge this as is as we at least have a framework for mono support in future.

Thanks @CodeHex - you're awesome!

**Pull request merged**
