### PR TITLE
Ensure RemoveProjectRoots works for assemblies that are run on a OS that differs from their build OS.

### LINKED ISSUE #152: ProjectRoots not being removed when build on Linux and hosted on Windows
### Describe the bug
When a project is build on Linux but hosted on Windows, the defined ProjectRoots are not being removed.

This is being caused by:
https://github.com/bugsnag/bugsnag-dotnet/blob/b4d91276f1e66d91381d37cb16fef4d8c7992d6b/src/Bugsnag/Middleware.cs#L40-L48

It checks if the last character of the ProjectRoot is equal to `DirectorySeparatorChar`. Because the project is build on Linux the final character in the root folder is `/` but its being ran on Windows so it checks for `\` instead.

Any reason why that particular check exists in the first place? The quickest solution would be to just remove it. Although if there is a reason for it, it should be altered so it checks for both `/` and `\` plus whatever the default separator character is.

### Environment
* Bugsnag version: 2.2.3
* .NET framework version: .NET 6

### PR DESCRIPTION
**Pull request by sgtfrankieboy**
## Goal

Fixes #152.

## Design

This design ensures that the ProjectRoots provided still get the seperatorChar appended to the end of the path no matter if its a Windows or Unix-based path.

## Changeset

The RemoveProjectRoots method now checks if a ProjectRoot provided is a Unix-based path or Windows and acts accordingly.

## Testing

I added in two tests for testing Unix-based paths to the MiddlewareTests file.

### CODE REVIEW

**Review by yousif-bugsnag — CHANGES_REQUESTED** [review]
Hi @sgtfrankieboy, thanks for the PR!

I think this needs a bit of tweaking for the case of Unix-style paths that already contain a trailing slash, e.g. `/app/`, as I think currently the prefix for these would end up as `/app/\`.

It looks like the new test scenarios are still checking Windows-style paths which is why this isn't being picked up.

**Comment by sgtfrankieboy** [comment]
Oh that was a pretty big brainfart on my part. Fixed the code and tests.

**Review by yousif-bugsnag — DISMISSED** [review]

**Review by yousif-bugsnag — APPROVED** [review]

**Comment by yousif-bugsnag** [comment]
Thanks for the contribution @sgtfrankieboy!

**Comment by yousif-bugsnag** [comment]
This has now been released in [v3.0.1](https://github.com/bugsnag/bugsnag-dotnet/releases/tag/v3.0.1) 🎉

**Pull request merged**
