### PR TITLE
Allow Bugsnag to be configured through appSettings instead of required custom configuration section

### PR DESCRIPTION
**Pull request by jwallace1983**
The high-level reasons for these changes were to simplify the initial code necessary to immediately start using Bugsnag in projects with the fewest steps as possible. There are 3 central commits to this pull request. As a result, to start using Bugsnag in this fork, I only need:
- Bugsnag package to be installed in the project
- An appSetting called "bugsnag.apiKey" in the web.config or app.config
- The "Bugsnag" namespace imported for the class being managed (ie: using Bugsnag;)
- Calling the "Notify()" extension on the exception (ie: ex.Notify();) 

As the existing projects are written today, for a product to implement BugSnag using the provided clients in the library (such as WebAPIClient, WebMVCClient, or WPFClient), the product must use the defined custom configuration sections. These custom configuration sections are clean and strongly typed - great in many scenarios. However, it creates a barrier for some development teams who may not be comfortable with custom configuration sections (which can be difficult to document and train how to use). It also means additional steps to begin using Bugsnag in a competitive market where you want your product to be as easily and quickly integrated as possible.

These minor changes create a new implementation of IConfigurationStorage to derive the Bugsnag settings from the appSettings section of an app.config or web.config file for a project. This means that once Bugsnag is installed from nuget, developers only need to add the api key to the appSettings of their project to immediately begin using Bugsnag.

The source code follows the existing naming convention of the IConfigurationStorage model with camel case applied to a prefix for the application name (bugsnag), then a dot, and finally the camel case of the configuration setting name. To define the api key, the key in the app setting would be "bugsnag.apiKey".

Several other popular error logging frameworks leverage extension methods to simplify the code base when reporting errors. It can also make things easier out of the box to report exceptions. This commit defines an ErrorExtensions static class that once a product includes "Bugsnag", the "Notify" method is extended onto any Exception objects that are available. Reporting an error now minimizes how much knowledge the developer must understand about the internals of Bugsnag (ie: BaseClient or the various static client classes). The developer must only import Bugsnag, then a single line such as "ex.Notify()" will send the exception.

The configuration for this extensions attempted to leverage the existing information provided by the various clients and done in a way to work with existing documentation on the Bugsnag site. The ErrorExtensions use a new enum, ClientTypes, to identify which client should be used to pass on the exception (and thus take advantage of the auto-appended details of the session or client). The client must be configured so that an MVC project won't use the Wpf client. The client type is configured within the Start method of each of the clients as well as the methods used when configuring global error handling. Therefore, if the user follows the Bugsnag docs for global handling on mvc/api/wpf projects, or calls the start method on the desired client when the app starts, the underlying settings are configured automatically.

### CODE REVIEW

**Comment by jwallace1983** [comment]
Please let me know what the process of reviewing pull requests. I'm happy to answer any questions you have. This would be an extremely useful set of features for our team.

**Comment by CodeHex** [comment]
Just my two cents......

I think its a great idea for using extension methods for reporting individual exceptions!

I also agree that its really quick, easy and familiar to add 
```xml
<add key="bugsnag.api" value="xxxxxxxxxx">
```
to any app.config or web.config and the client is configured! The app storage looks good.

Its looks like there is not much control over what client is used for the extension methods. The methods rely heavily on the initial client (WPF, WebAPI or MVC) being started up as expected before any extension methods are called and the extension static class is initialized. But in cases when people want to use them in a custom way e.g. use there own `BaseClient`, or only use the `Notify()` methods on the web clients, the extension methods I think could use different clients with potentially different config (is that true?). Also I guess there is no way to specify or swap out the client to use, but that might be OK for this use.

Also if you use the `SingletonBaseClient` set the client and custom configure it, the first time you call an extension method, it would be written over with a brand new one (is that right?)

Definitely think these additions would makes it easier and quicker to start using Bugsnag.

What do you think @snmaynard ?

**Comment by jwallace1983** [comment]
Any idea whether this will be a candidate to include? We'd love to start using these features natively out of nuget across all our apps!

**Comment by jwallace1983** [comment]
@CodeHex, @snmaynard - Any idea whether this can be included in a future version? I would still love to see something like this out of the box. I'm happy to try to refactor the approach if you think another way may be better.

**Comment by martin308** [comment]
@jwallace1983 thanks for your contribution, sorry it has taken us so long to get around to addressing this PR. We are about to release a new version of the notifier which will make this PR impossible to merge. Let us know how you find the new version

**Pull request closed without merging**
